dist: trusty
sudo: required
services:
  - docker
language: node_js
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
- sudo apt-get update
- sudo apt-get install google-chrome-stable
branches:
  only:
  - master
node_js:
- '7'
- '8'
- '9'
script:
- yarn test
- docker build -t pomle/megaman .
after_success:
- yarn run upload-coverage
